version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 2 7,21 * *"
    cooldown:
      semver-patch-days: 5
      semver-minor-days: 7
      semver-major-days: 14
    groups:
      non-major-updates:
        update-types:
          - "patch"
          - "minor"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 5 7,21 * *"
    cooldown:
      default-days: 7
    exclude-paths:
      - ".github/workflows/release.yml"
      - ".github/workflows/scan.yml"
    labels:
      - "dependencies"
    commit-message:
      prefix: "ci"
