[advisories]
ignore = [
    "RUSTSEC-2024-0436",
    "RUSTSEC-2025-0057",
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]

[bans]
deny = [
    "openssl",
]
