name: audit

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 2,6'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dhth/composite-actions/.github/actions/cargo-deny@main
