name: audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 6'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: cargo audit
        run: cargo audit
